### ISSUE TITLE
update AdSet status only works using "status" field which was removed in v2.5

### ISSUE THREAD

**Issue by iditgolden** [facebook/facebook-python-ads-sdk#113]
AdSet status can be changed only by adding "status" key to the adset obj but this field was **replaced** by configured_status in version 2.5.
changing the configured_status does not update the adset status, only "status" (which no longer exist in the Field attributes of AdSet)

**Comment by iditgolden** [comment]
same thing with updating Campaign

**Comment by paulbain** [comment]
you should checkout the examples in our documentation. You set the status by passing it in a dictionary when calling the remote_create/update/save functions:

    from facebookads.objects import Campaign

    campaign = Campaign(parent_id='act_<AD_ACCOUNT_ID>')
    campaign.update({
        Campaign.Field.name: 'My First Campaign',
        Campaign.Field.objective: '<OBJECTIVE>',
    })

    campaign.remote_create(params={
        'status': Campaign.Status.paused,
    })
    print(campaign)

**Comment by iditgolden** [comment]
yes, but there is no "status" attribute anymore in adSet and Campaign objects's Fields, only "configured_status" and "effective_status"

campaign.remote_create(params={
   ** 'status' **: Campaign.Status.paused,
})

**Comment by paulbain** [comment]
You need to read the `configured_status` and `effective_status`, yet update the `configured_status` field by passing a parameter called `status` when making an update. 

Does that answer your question?

**Comment by iditgolden** [comment]
yes, but why there is no "status" field in the fields list?
status = 'status'

**Comment by paulbain** [comment]
it's because the object does not have a field call status, check the set of fields in the documentation:
https://developers.intern.facebook.com/docs/marketing-api/reference/ad-campaign-group

Status is not separated into the two fields, the `configured_status` and `effective_status`. The write path uses a parameter *which is not part of the object* to set the `configured_status`.

**Comment by iditgolden** [comment]
@paulbain : thank you for your response. the link isn't available though.

**Comment by hockeybuggy** [comment]
Hey @iditgolden Are you sure that it should be `configured_status`? We are having some issues related to this. I think the link @paulbain was trying to post was:

https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-group#Creating

The example there is verbatim what @paulbain said above. You're right that only `effective_status` and `configured_status` is listed in the "Reading" parameters table but, you can also see `status` in the table of parameters in the "Creating" and "Updating" sections.

**Comment by paulbain** [comment]
Yes you write the `status` field using the parameter `status` but you read it using both `configured_status` being what you set, and `effective_status` is what it's considered as due to other configuration of your ads. Hopefully we can make writing `effective_status` work at some point for consistency.

**Comment by hockeybuggy** [comment]
I created PR #147 that should add the `status` field to the effected objects. @iditgolden @paulbain Would you mind taking a look? :smile:
