### ISSUE TITLE
AbstractCrudObject does not pass self._api into FacebookRequest ctor

### ISSUE THREAD

**Issue by scottanderson42** [facebook/facebook-python-ads-sdk#171]
This breaks the use of specific API objects instead of setting the default API for remote_read, remote_create, remote_update, remote_delete.

**Comment by rituparnamukherjee** [comment]
These are the older CRUD implementations. You can checkout the new api_create, api_get, api_delete, api_update methods in the individual classes. These flow the api instances. You can use this for specifying api instances instead.

**Comment by scottanderson42** [comment]
@rituparnamukherjee Thanks for the reply. So the api_* methods now supersede the use of remote_*?

The remote_* methods are not marked as deprecated. At any rate, any existing code that uses these methods will no longer work if the default api is not being set.

**Comment by rituparnamukherjee** [comment]
Good point. Taking a look.

**Comment by mattkahl** [comment]
If the `remote_*` methods are, in fact, deprecated it seems necessary to do the following:
1. Denote them as such (as opposed to the implicit description of the "new" methods) in the README
2. Update the code samples in the README to use `api_*` instead of `remote_*`

The sooner that's explicitly stated, the less time both need to be offered.

**Comment by rituparnamukherjee** [comment]
Actually they are not deprecated, in the sense that you can choose to call them. They are inherently calling the api_* methods internally and this is done so that your current code doesn't break. 

We will modify the READ me and add example with details around these methods very soon.

**Comment by JiamingFB** [comment]
Hi scottanderson42,

It is a valid issue that in AbstractCrudObject we didn't pass the api object when constructing the FacebookRequest object. And we'll fix for that. Thanks!

Just to double check, this bug seems to only affect situation when the calling object doesn't have api_* method in its own class definition, in which case we fall back to constructing a ad-hoc FacebookRequest in AbstractCrudObject. Is this what you're experiencing? (If you're experiencing more than that, please let us know and we'll need some further investigation)

**Comment by rituparnamukherjee** [comment]
Fixed by last commit

**Comment by scottanderson42** [comment]
@JiamingFB Yes, we had an object that had only remote_read in the class definition.

@rituparnamukherjee Thanks!
