### ISSUE TITLE
Programmatically request access token

### ISSUE THREAD

**Issue by bookface-ads** [facebook/facebook-python-ads-sdk#176]
In the equivalent PHP client, there is a way to request access tokens [programmatically](https://developers.facebook.com/docs/marketing-api/quickstart#access-token). What needs to be done to achieve the same in python?

For the time being, what is a common solution to this problem? To generate an access token by hand periodically?

**Comment by rituparnamukherjee** [comment]
The PHP client you are mentioning is the Facebook PHP sdk. It is different from the PHP ads sdk. You can use graph explorer to generate the user access token and convert it into a long lived access token. So that will be valid for 90 days. https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension 

There is no way of doing this through the SDK.
