### ISSUE TITLE
Auto-generated classes or no moving forward?

### ISSUE THREAD

**Issue by tejasmanohar** [facebook/facebook-python-ads-sdk#197]
Some resources have this docstring, some don't.

```
"""
This class is auto-generated.

For any issues or feature requests related to this class, please let us know on
github and we'll fix in our codegen framework. We'll not be able to accept
pull request for this class.
"""
```

Moving forward, is the intention to auto-generate the resource classes? If so, is the auto-generation framework/toolkit planning to be open-sourced and documented so that others can contribute to the library?

**Comment by tejasmanohar** [comment]
If the plan is not to auto-generate moving forward, would you be open to PRs that rewrite these classes?

**Comment by rituparnamukherjee** [comment]
Unfortunately, the autogenrated framework, cannot be open sourced. Since the framework used Graph API layer for generating this SDK, it wont be possible to open source them.

But if there are features modifications to the adobjects that you will will be helpful for the design, you can submit the suggestion as an issue and we can consider adding it to the framework.

**Comment by tejasmanohar** [comment]
I see. That's unfortunate but glad you're open to suggestions
