### ISSUE TITLE
Reasoning behind removing `facebookads.objects`

### ISSUE THREAD

**Issue by tejasmanohar** [facebook/facebook-python-ads-sdk#199]
https://github.com/facebook/facebook-python-ads-sdk#sdk-structure

Hm, I think this should be kept in the API. It helps with scoping / readability `facebookads.Blah`

**Comment by rituparnamukherjee** [comment]
@tejasmanohar 

The reason for changing the SDK structure is to separate classes into independent files, it actually helps with readability. 

You will notice that a large number of classes which are under adobjects are missing from the objects file, the reason being all these new objects are being auto-generated using a framework which is based off of the graph api that we have. This is so that the SDKs are very closely compatible to what our API has to offer. WIth the objects file this was manual and that is why without such close comaptibilty. 

Another reason behind this kind of structure was to have similar conventions and SDK tree structure for all languages. 

Keeping the objects.py file will mean having to maintain it manually, which will be counter productive :)
You can choose to have this file in your local repo though, if it helps with your development.

**Comment by tejasmanohar** [comment]
Can't objects.py be generated automatically or contain dynamic code that reads objects? see https://github.com/troygoode/node-require-directory for comparable example. Anyways, fair point- the user can implement this
