### ISSUE TITLE
ImportError: cannot import name AdCampaign

### ISSUE THREAD

**Issue by lycheng** [facebook/facebook-python-ads-sdk#205]
I try this [example](https://github.com/facebook/facebook-python-ads-sdk/blob/master/examples/create_ad.py)

and get 

```
    from facebookads.objects import (
ImportError: cannot import name AdCampaign
```

And I found that there is no AdCampaign in [objects.py](https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/objects.py). Can you update the example codes?

**Comment by rituparnamukherjee** [comment]
Hi @Iycheng,

Thanks for pointing this out. The example folder contains some outdated examples. Will update soon.

**Comment by zacktaiwan** [comment]
when to update the outdated example code?

**Comment by wuxie2015** [comment]
So how can I use it now?

**Comment by uppercasebrands** [comment]
@wuxie2015 AdCampaign has been renamed to Campaign. You can do
`from facebookads.adobjects.campaign import Campaign`

Also, the current-and most recent- pip package version 2.9.1 is partially broken. You should upgrade your facebookads package from github repo. From your commandline, try:

`pip install --upgrade git+https://github.com/facebook/facebook-python-ads-sdk.git`

**Comment by wuxie2015** [comment]
So when


At 2017-06-05 15:35:48, "Uppercase Brands Engineering" <notifications@github.com> wrote:


@wuxie2015 AdCampaign has been renamed to Campaign. You can do
from facebookads.adobjects.campaign import Campaign

Also, the current-and most recent- pip package version 2.9.1 is partially broken. You should upgrade your facebookads package from github repo. From your commandline, try:

pip install --upgrade git+https://github.com/facebook/facebook-python-ads-sdk.git

**Comment by wuxie2015** [comment]
When I was using this API, it says


  Message: Call was not successful
  Method:  GET
  Path:    https://graph.facebook.com/v2.9/1821114030/adaccounts
  Params:  {'summary': 'true'}


  Status:  400
  Response:
    {
      "error": {
        "message": "Invalid appsecret_proof provided in the API argument", 
        "code": 100, 
        "type": "GraphMethodException", 
        "fbtrace_id": "E88xxnY/05B"
      }
    }


So Why did I got this? I want to use the marketing api, how can I get my access token to access the auth?here is my code ,is that any problems in it?
# -*- coding: utf-8 -*-
from facebookads.api import FacebookAdsApi
from facebookads.adobjects.user import User
import urllib
import re

my_app_id = '<MY APP ID>'
my_app_secret = '<MY SECRET>'
url = "https://graph.facebook.com/oauth/access_token?client_id=%s&client_secret=%s&grant_type=client_credentials"%(my_app_id,my_app_secret)
f = urllib.urlopen(url)
token = f.read()
token_dict = eval(token)
my_access_token = token_dict['access_token']
#proxies = {'http': '127.0.0.1:8087', 'https': '127.0.0.1:8087'} # add proxies if needed
FacebookAdsApi.init(my_app_id, my_app_secret, my_access_token)
me = User(fbid='<MY FBID>')
my_accounts = list(me.get_ad_accounts())
print(my_accounts)
type(my_accounts[0])



At 2017-06-05 15:35:48, "Uppercase Brands Engineering" <notifications@github.com> wrote:


@wuxie2015 AdCampaign has been renamed to Campaign. You can do
from facebookads.adobjects.campaign import Campaign

Also, the current-and most recent- pip package version 2.9.1 is partially broken. You should upgrade your facebookads package from github repo. From your commandline, try:

pip install --upgrade git+https://github.com/facebook/facebook-python-ads-sdk.git

**Comment by wuxie2015** [comment]
I'm sorry for the last emai which has not been complated and sent wrongly
What's more, when I was using the fbid got from https://developers.facebook.com/tools/explorer/?method=GET&path=me%3Ffields%3Did%2Cname&version=v2.9
it says
  Message: Call was not successful
  Method:  GET
  Path:    https://graph.facebook.com/v2.9/10207136520370978/adaccounts
  Params:  {'summary': 'true'}


  Status:  400
  Response:
    {
      "error": {
        "message": "Unsupported get request. Object with ID '10207136520370978' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api", 
        "code": 100, 
        "type": "GraphMethodException", 
        "fbtrace_id": "AphZhmbQ7lF"
      }
    }


Did I got the wrong fbid? Where can I get my correct fbid?Or does it due to I haven't set the correct permission?

At 2017-06-05 15:35:48, "Uppercase Brands Engineering" <notifications@github.com> wrote:


@wuxie2015 AdCampaign has been renamed to Campaign. You can do
from facebookads.adobjects.campaign import Campaign

Also, the current-and most recent- pip package version 2.9.1 is partially broken. You should upgrade your facebookads package from github repo. From your commandline, try:

pip install --upgrade git+https://github.com/facebook/facebook-python-ads-sdk.git
