### ISSUE TITLE
Support for testing against this project without touching live accounts.

### ISSUE THREAD

**Issue by ghedsouza** [facebook/facebook-python-ads-sdk#244]
I am about to start using this repo for a project, and I would like some advice regarding how I can write unit/integration tests for a project that depends on `facebook-python-ads-sdk`. Integration tests are vital for ensuring quality, so it's really important to get this right.

The only methods I can see right now are:

1. Create a test version of a Facebook user account, an App, an Ads account (which unfortunately seems to require a credit card), and a Facebook Page, and then use these within the test environment for integration tests for my own project (after generating all the required tokens). This would be fine, but I'm not sure if this is even technically allowed by Facebook according to their own TOS. The requirement for a credit card to setup an Ads account also is not ideal for use in a testing environment.

2. Mock everything out. This of course requires no account setup on Facebook, and would allow me to test my own code, but is going be hard to maintain, and of course offers no guarantees that my project will actually work with the Marketing API.

I would appreciate some direction from the Facebook team here, or anyone else who is working with this repo. cc @m-vdb.

**Comment by m-vdb** [comment]
I think you definitely need both. We have mocked unit tests and we have 3 accounts (dev / test / production), we use the first 2 for manual testing. I think it's ok to have a testing account (I don't see what's the issue with FB). We currently only run the [integration tests of this repo](https://github.com/facebook/facebook-python-ads-sdk/blob/2.6.2.1/facebookads/test/integration.py) but it's possible that in a near future we write tests ourselves. Also, if you design a system complex enough, you might need your ads to live a little bit on your test account and they could spend some money, so that's why the credit card is required.

**Comment by JiamingFB** [comment]
I think you can go with 1 and set up a test account. You don't necessarily need to create a fake Facebook user (which might be banned if detected). Instead, you can create a business and then create an ad account under that business. Remember to set an account spending limit on the test account to prevent accidental spending.

Developers have been asking for Ads API testing environment for quite a long time. Although it's not supported yet, it could change soon. Please keep an eye on the Marketing API News for latest update: https://developers.facebook.com/ads/blog/ .
