### ISSUE TITLE
Set Limit

### ISSUE THREAD

**Issue by nicoschuck** [facebook/facebook-python-ads-sdk#288]
I want to get all AdAccounts which are connected to my business Account.
If i do the following code i get only 25 of the accounts:

```
FacebookAdsApi.init(my_app_id, my_app_secret, my_access_token)
me = AdUser(fbid='me')
accounts = me.get_ad_accounts()
```
In the Explorer i can do it on this way:

`me?fields=adaccounts.limit(350){name}`

In the examples i can´t find a solution. Has anyone a guide for reading the data from the Marketing API?

**Comment by JiamingFB** [comment]
Hi @nicoschuck, 

This is about the pagination of Facebook API. For Marketing API, I think the default page size is 25.

In Python SDK, we fetch one page for each API call. BUT, if you do a for-loop for the result (accounts), we auto-fetch the next page and next page until it reaches end. Please see the code in Cursor class. This means:
1. If you do `for account in accounts`, you will loop over all accounts under your name (more than 25)
2. If you check `len(accounts)`, you will get 25 in your case, because auto-fetch is not considered.
3. If you want to override the default limit (25), you can try this (not recommended because this might be slow):
` 
accounts = me.get_ad_accounts(params={'limit': 350})
`

Let me know if you have any further questions.

**Comment by nicoschuck** [comment]
Hi @JiamingFB ,
thanks for your fast answer, all the possibilitys works fine. Do you have examples for using the marketing api by python. 
For example i need to know how i can set a breakdown like day, age, gender...
Or how i can set the fields i need like insights, name ...
Thanks a lot for your help!
Greeds,
Nico
