### ISSUE TITLE
Broken since API 2.9

### ISSUE THREAD

**Issue by alimony** [facebook/facebook-python-ads-sdk#309]
I get the "You are calling a deprecated version of the Ads API" error since new apps need version 2.9 of the API (released a couple of days ago) but this SDK is still on 2.8.

**Comment by christopher-charles** [comment]
I get this same problem too. Any idea when you'll have a fix for it?

**Comment by advance512** [comment]
What's up with you guys? Is this seriously an official Facebook SDK for one of its most important APIs?

**Comment by md-contratado** [comment]
Is it possible to manage my campaigns (example: turn it on/off) via API without using the SDK?

**Comment by guruscott** [comment]
Same issue here...

**Comment by guruscott** [comment]
Went into apiconfig.py and changed the following (see below). Seems to work now... *shrug*. Bewildered why a simple change like the one below wouldnt be included in any notes anywhere, if indeed this solves the issue above.

ads_api_config = {
  #'API_VERSION': 'v2.8', #changed 25-04-17
  'API_VERSION': 'v2.9', 
  'SDK_VERSION': 'v2.8.1',
  'STRICT_MODE': False
}

**Comment by daphyFB** [comment]
This issue happens when a new app is created between the API 2.9 release date and API SDK 2.9 release date. We are sorry that there was a delay on our side of releasing SDK 2.9. Since we did release SDK 2.9 on 04/24/2017, hopefully this issue has gone away for you.

We're currently working on shortening the release delay internally, and will also work with the documentation team to see how we can improve the error message for the next release.

Please feel free to reopen the issue if you have further questions. Thank you for reporting SDK issues, and thanks again for your patience.
