### ISSUE TITLE
examples.read_objects.py completely out of date

### ISSUE THREAD

**Issue by DannyLee12** [facebook/facebook-python-ads-sdk#338]
In the example: read_objects.py, none of the example code runs.

There are a few issues:
1. `from facebookads import FacebookSession` should be `from facebookads.session import FacebookSession`
2. `from facebookads import FacebookAdsApi` should be `from facebookads.api import FacebookAdsApi`
3. `from facebookads. import (AdUser,Campaign)` should be something else.

Are there any more up-to-date examples that are being used? This doc was updated in 2014!

**Comment by uppercasebrands** [comment]
@DannyLee12 https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/__init__.py already imports FacebookSession and FacebookAdsApi as your example, which means that if you actually can just say "from facebookads import FacebookSession" or "from facebookads import FacebookAdsApi". In order to run read_objects.py successfully, you need to make sure that you either did "pip install facebook-ads" or you defined the location of your facebook sdk in your PYTHONPATH. If this does not work, feel free to attach your commandline output and perhaps we can help you.
