### ISSUE TITLE
Cannot create product catalogs with sdk v2.11.1

### ISSUE THREAD

**Issue by x8lucas8x** [facebook/facebook-python-ads-sdk#415]
In the last 2.11 release, you've removed the create_product_catalog method from the Business class. But not only that, you've also removed the api_create method from the ProductCatalog class, which means that in theory we are only left with remote_create() for creating product catalogs. But wait, according to https://developers.facebook.com/docs/marketing-api/reference/product-catalog the new product catalog endpoint is /{business_id}/owned_product_catalogs. Guess what, the same 2.11 release is referring to the old endpoint (i.e. /{business_id}/product_catalogs).

**Comment by brandonkane** [comment]
@x8lucas8x were you able to find a workaround for this?  We're working to migrate to 2.11 now and this is blocking us.

**Comment by brandonkane** [comment]
Facebook's documentation [here](https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/product-catalog#create-product-catalog) clearly indicates that .remote_create() is the correct way to do it, but I've run into the exact same error as you with the SDK still using the old endpoint.

**Comment by brandonkane** [comment]
This was logged with our FMP direct support channel and acknowledged as a bug.  Unfortunately the bug was closed since Facebook doesn't support their SDKs through that channel, so the only remaining open ticket is here.  The support rep did confirm that Facebook is aware of the issue and is tracking it internally, but since there has been no response here from Facebook we have no way to know if that is correct.

The retirement of 2.10 is rapidly approaching, so this needs to get resolved and a new 2.11 release issues well in advance of the Feb 5 deadline for getting off of 2.10.

**Comment by brandonkane** [comment]
I see there have been some commits today adding back the missing functions and correcting the broken endpoint.  The build is also passing again which is great.

The docs I think are still out of date since they use the parent_id in the constructor which leads to a deprecation warning.

Would be great if we could get 2.11.3 published to pypi, the latest version on there is still 2.11.1.  See https://pypi.python.org/pypi/facebookads/

**Comment by xiaotchen** [comment]
Hi @brandonkane, I just published 2.11.3 to pypi. Thanks!

**Comment by brandonkane** [comment]
Thanks @xiaotchen!  Would be great if we could also get a release with the syntax errors fixed as well.  See https://github.com/facebook/facebook-python-ads-sdk/issues/420
