### ISSUE TITLE
SSL Warning in Python 2.7.9

### ISSUE THREAD

**Issue by cscanlin** [facebook/facebook-python-ads-sdk#42]
I am getting a warning I have never seen before when creating an audience in SDK version 2.3.1, Python version 2.7.9:
>InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

After reading through the link, it appears that this is related to an incompatibility with urllib3 and Python 2.7.

Is there actually a security hole here or is this just an overly-cautious warning?

**Comment by agriffis** [comment]
Are you sure you got this on Python 2.7.9? It should be fixed on that version.

In any case, it's *probably* not a security issue for connecting to the Graph API, because graph.facebook.com doesn't use either TLS compression or SNI. See https://github.com/shazow/urllib3/issues/557#issuecomment-94956162 and https://www.ssllabs.com/ssltest/analyze.html?d=graph.facebook.com

**Comment by ebzlo** [comment]
You can fix this issue with the following pip command:
`pip install requests[security]`

More info: http://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent
